import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <div className="w-full bg-gray-800 p-4 sticky top-0 z-50">
                    <div className="container mx-auto flex justify-between items-center">
                        {/* Logo Section */}
                        <div className="flex items-center text-white">
                            <Image
                                src="/path-to-your-logo.png"
                                alt="Logo"
                                width={32}
                                height={32}
                            />
                            <span className="text-lg font-bold">Your Logo</span>
                        </div>

                        {/* Links Section */}
                        <div className="flex space-x-4">
                            <Link
                                href="/media-personality"
                                className="text-white hover:text-gray-300"
                            >
                                Personnalité Médiatique
                            </Link>
                            <Link
                                href="/career"
                                className="text-white hover:text-gray-300"
                            >
                                Carrière
                            </Link>
                            <Link
                                href="/films"
                                className="text-white hover:text-gray-300"
                            >
                                Films
                            </Link>
                            <Link
                                href="/books"
                                className="text-white hover:text-gray-300"
                            >
                                Livres
                            </Link>
                        </div>
                    </div>
                </div>
            </body>
        </html>
    );
}
